# Generated by Django 3.0.8 on 2020-08-12 17:05

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200809_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('cards', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('description', wagtail.core.blocks.CharBlock(max_length=140, required=True)), ('url', wagtail.core.blocks.CharBlock(max_length=150, required=True)), ('button_page_name', wagtail.core.blocks.CharBlock(max_length=40, required=True))])))]))], blank=True, null=True),
        ),
    ]
