# Generated by Django 3.0.8 on 2020-08-13 06:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0008_auto_20200812_1705'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='ThemesPage',
        ),
    ]
